added ci-cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -25,20 +25,20 @@ jobs:
           
       - name: Checking required secrets keys
         run: |
-          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "Missing DOCKER_USERNAME" && exit 1; fi
-          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "Missing DOCKERHUB_TOKEN" && exit 1; fi
+          if [ -z "${{ secrets.DOCKER_USERNAME}}" ]; then echo "Missing DOCKER_USERNAME" && exit 1; fi
+          if [ -z "${{ secrets.DOCKER_PASSWORD}}" ]; then echo "Missing DOCKERHUB_TOKEN" && exit 1; fi
       
       - name: Building Docker image
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/churning-system Churn-system/dockerfile
+          docker build -t ${{ secrets.DOCKER_USERNAME}}/churning-system Churn-system/dockerfile
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          username: ${{ secrets.DOCKER_USERNAME}}
+          password: ${{ secrets.DOCKER_PASSWORD}}
 
       - name: Tagging & pushing image
         run: |
-          docker tag ${{ secrets.DOCKER_USERNAME }}/Churning-system:latest ${{ secrets.DOCKER_USERNAME }}/Churning-system:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/Churning-system:latest
+          docker tag ${{ secrets.DOCKER_USERNAME}}/Churning-system:latest ${{ secrets.DOCKER_USERNAME}}/Churning-system:latest
+          docker push ${{ secrets.DOCKER_USERNAME}}/Churning-system:latest
