add ci-cd pipline

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -22,21 +22,21 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r Churn-system/requirements.txt
-        
-      - name: Building Docker image
-        run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/Churning-system Churn-system/Dockerfile
-
+          
       - name: Checking required secrets keys
         run: |
           if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "Missing DOCKER_USERNAME" && exit 1; fi
-          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "Missing DOCKERHUB_TOKEN" && exit 1; fi
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then echo "Missing DOCKERHUB_TOKEN" && exit 1; fi
+      
+      - name: Building Docker image
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/churning-system Churn-system/dockerfile
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Tagging & pushing image
         run: |
